import { Component, OnInit } from '@angular/core';
import { ClusterDataService } from '../services/cluster-data.service';
import '@cds/core/button/register.js';



@Component({
  selector: 'app-cluster-data',
  templateUrl: './cluster-data.component.html',
  styleUrls: ['./cluster-data.component.css'],
  providers: [ClusterDataComponent]
})


export class ClusterDataComponent implements OnInit {
  cloudzones = [
    {
       "CloudZone":"usljv04xp2vcawir1002.fiserv.one / usljv04-w2-dc",
       "Description":"Production Lewisville",
       "Metric CPU Ratio Max":"2.5",
       "Metric Memory Free %":"0",
       "Metric Disk Free %":"30",
       "Clusters":[
          {
             "Name":"usljv04ep2genclu0001",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"34570.33",
             "Memory Free %":"70.40",
             "CPU (Virtual)":3886,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.4",
             "Datastore":"usljv04ep2genclu0001-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1105.29",
             "Disk Free %":"82.40",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usljv04ep2genclu0012",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"41014.77",
             "Memory Free %":"83.52",
             "CPU (Virtual)":2498,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.2",
             "Datastore":"usljv04ep2genclu0012-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1209.93",
             "Disk Free %":"90.20",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usljv04ep2genclu0003",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"41873.70",
             "Memory Free %":"85.27",
             "CPU (Virtual)":1523,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"1.3",
             "Datastore":"usljv04ep2genclu0003-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1276.44",
             "Disk Free %":"95.16",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usljv04ep2genclu0014",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"41778.97",
             "Memory Free %":"85.08",
             "CPU (Virtual)":1827,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"1.6",
             "Datastore":"usljv04ep2genclu0014-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1274.89",
             "Disk Free %":"95.04",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usljv04ep2genclu0008",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"39557.92",
             "Memory Free %":"80.55",
             "CPU (Virtual)":2181,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"1.9",
             "Datastore":"usljv04ep2genclu0008-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1238.55",
             "Disk Free %":"92.34",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usljv04ep2genclu0004",
             "HostCount":"31",
             "Memory Total (GiB)":"47573.33",
             "Memory Free (GiB)":"30623.33",
             "Memory Free %":"64.37",
             "CPU (Virtual)":3920,
             "CPU (Physical)":1116,
             "CPU Ratio (vCPU:pCPU)":"3.5",
             "Datastore":"usljv04ep2genclu0004-vsan",
             "Disk Total (TiB)":"1299.45",
             "Disk Free (TiB)":"1190.55",
             "Disk Free %":"91.62",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usljv04ep2genclu0010",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"34426.45",
             "Memory Free %":"70.10",
             "CPU (Virtual)":2180,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"1.9",
             "Datastore":"usljv04ep2genclu0010-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"733.96",
             "Disk Free %":"54.72",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"admin-disabled"
          },
          {
             "Name":"usljv04ep2genclu0009",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"34409.95",
             "Memory Free %":"70.07",
             "CPU (Virtual)":2696,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.3",
             "Datastore":"usljv04ep2genclu0009-vsan",
             "Disk Total (TiB)":"1330.89",
             "Disk Free (TiB)":"957.84",
             "Disk Free %":"71.97",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usljv04ep2genclu0005",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"30737.95",
             "Memory Free %":"62.59",
             "CPU (Virtual)":4726,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"4.1",
             "Datastore":"usljv04ep2genclu0005-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1221.53",
             "Disk Free %":"91.07",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usljv04ep2genclu0002",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"35776.95",
             "Memory Free %":"72.85",
             "CPU (Virtual)":3336,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.9",
             "Datastore":"usljv04ep2genclu0002-vsan",
             "Disk Total (TiB)":"1288.97",
             "Disk Free (TiB)":"1086.47",
             "Disk Free %":"84.29",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usljv04ep2genclu0006",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"39677.95",
             "Memory Free %":"80.80",
             "CPU (Virtual)":2226,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"1.9",
             "Datastore":"usljv04ep2genclu0006-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1255.26",
             "Disk Free %":"93.58",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usljv04ep2genclu0013",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"40822.16",
             "Memory Free %":"83.13",
             "CPU (Virtual)":2631,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.3",
             "Datastore":"usljv04ep2genclu0013-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1235.76",
             "Disk Free %":"92.13",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usljv04ep2genclu0011",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"41551.97",
             "Memory Free %":"84.61",
             "CPU (Virtual)":2534,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.2",
             "Datastore":"usljv04ep2genclu0011-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1244.07",
             "Disk Free %":"92.75",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usljv04ep2genclu0007",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"35051.20",
             "Memory Free %":"71.38",
             "CPU (Virtual)":3607,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.1",
             "Datastore":"usljv04ep2genclu0007-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1145.04",
             "Disk Free %":"85.36",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          }
       ]
    },
    {
       "CloudZone":"uschd01xl2vcawir1001.fiserv.one / uschd01n-wld1-vdc",
       "Description":"Nonproduction Chandler",
       "Metric CPU Ratio Max":"7",
       "Metric Memory Free %":"-20",
       "Metric Disk Free %":"30",
       "Clusters":[
          {
             "Name":"uschd01en2genclu0001",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"28033.13",
             "Memory Free %":"57.08",
             "CPU (Virtual)":4085,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.5",
             "Datastore":"uschd01en2genclu0001-vsan",
             "Disk Total (TiB)":"1341.37",
             "Disk Free (TiB)":"1065.56",
             "Disk Free %":"79.44",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          }
       ]
    },
    {
       "CloudZone":"uschd01xp2vcawir1002.fiserv.one / uschd01p-wld2-vdc",
       "Description":"Production Chandler",
       "Metric CPU Ratio Max":"2.5",
       "Metric Memory Free %":"0",
       "Metric Disk Free %":"30",
       "Clusters":[
          {
             "Name":"uschd01ep2genclu0009",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"49059.70",
             "Memory Free %":"99.90",
             "CPU (Virtual)":19,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.0",
             "Datastore":"uschd01ep2genclu0009-vsan",
             "Disk Total (TiB)":"1334.38",
             "Disk Free (TiB)":"1316.09",
             "Disk Free %":"98.63",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"uschd01ep2genclu0003",
             "HostCount":"31",
             "Memory Total (GiB)":"47573.33",
             "Memory Free (GiB)":"31845.56",
             "Memory Free %":"66.94",
             "CPU (Virtual)":3539,
             "CPU (Physical)":1116,
             "CPU Ratio (vCPU:pCPU)":"3.2",
             "Datastore":"uschd01ep2genclu0003-vsan",
             "Disk Total (TiB)":"1257.53",
             "Disk Free (TiB)":"984.27",
             "Disk Free %":"78.27",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"uschd01ep2genclu0005",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"22329.95",
             "Memory Free %":"45.47",
             "CPU (Virtual)":6073,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"5.3",
             "Datastore":"uschd01ep2genclu0005-vsan",
             "Disk Total (TiB)":"1330.89",
             "Disk Free (TiB)":"1174.95",
             "Disk Free %":"88.28",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"uschd01ep2genclu0004",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"32423.20",
             "Memory Free %":"66.02",
             "CPU (Virtual)":3768,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.3",
             "Datastore":"uschd01ep2genclu0004-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1139.61",
             "Disk Free %":"84.96",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"uschd01ep2genclu0007",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"45953.70",
             "Memory Free %":"93.58",
             "CPU (Virtual)":842,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.7",
             "Datastore":"uschd01ep2genclu0007-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1220.05",
             "Disk Free %":"90.96",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"uschd01ep2genclu0002",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"37169.91",
             "Memory Free %":"75.69",
             "CPU (Virtual)":3134,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.7",
             "Datastore":"uschd01ep2genclu0002-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1195.06",
             "Disk Free %":"89.09",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"uschd01ep2genclu0008",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"48232.95",
             "Memory Free %":"98.22",
             "CPU (Virtual)":186,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.2",
             "Datastore":"uschd01ep2genclu0008-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1322.71",
             "Disk Free %":"98.61",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"uschd01ep2genclu0006",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"44732.70",
             "Memory Free %":"91.09",
             "CPU (Virtual)":1318,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"1.1",
             "Datastore":"uschd01ep2genclu0006-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1058.13",
             "Disk Free %":"78.88",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"uschd01ep2genclu0001",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"36648.45",
             "Memory Free %":"74.63",
             "CPU (Virtual)":3322,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.9",
             "Datastore":"uschd01ep2genclu0001-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1121.65",
             "Disk Free %":"83.62",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          }
       ]
    },
    {
       "CloudZone":"usoma01xp2vcawir1002.fiserv.one / usoma01p-wld2-vdc",
       "Description":"Production Omaha",
       "Metric CPU Ratio Max":"2.5",
       "Metric Memory Free %":"0",
       "Metric Disk Free %":"30",
       "Clusters":[
          {
             "Name":"usoma01ep2genclu0005",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"29090.26",
             "Memory Free %":"59.24",
             "CPU (Virtual)":5045,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"4.4",
             "Datastore":"usoma01ep2genclu0005-vsan",
             "Disk Total (TiB)":"1299.45",
             "Disk Free (TiB)":"1035.60",
             "Disk Free %":"79.70",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usoma01ep2genclu0002",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"31973.54",
             "Memory Free %":"65.11",
             "CPU (Virtual)":4111,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.6",
             "Datastore":"usoma01ep2genclu0002-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1028.46",
             "Disk Free %":"76.67",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usoma01ep2genclu0006",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"45269.20",
             "Memory Free %":"92.18",
             "CPU (Virtual)":784,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.7",
             "Datastore":"usoma01ep2genclu0006-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1222.72",
             "Disk Free %":"91.16",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usoma01ep2genclu0007",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"46611.70",
             "Memory Free %":"94.92",
             "CPU (Virtual)":618,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.5",
             "Datastore":"usoma01ep2genclu0007-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1284.64",
             "Disk Free %":"95.77",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usoma01ep2genclu0003",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"36721.95",
             "Memory Free %":"74.78",
             "CPU (Virtual)":3236,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.8",
             "Datastore":"usoma01ep2genclu0003-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"922.59",
             "Disk Free %":"68.78",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usoma01ep2genclu0008",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"46580.94",
             "Memory Free %":"94.85",
             "CPU (Virtual)":966,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.8",
             "Datastore":"usoma01ep2genclu0008-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1308.58",
             "Disk Free %":"97.56",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usoma01ep2genclu0001",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"29559.20",
             "Memory Free %":"60.19",
             "CPU (Virtual)":4020,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.5",
             "Datastore":"usoma01ep2genclu0001-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1179.05",
             "Disk Free %":"87.90",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usoma01ep2genclu0009",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"48705.20",
             "Memory Free %":"99.18",
             "CPU (Virtual)":179,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.2",
             "Datastore":"usoma01ep2genclu0009-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1319.29",
             "Disk Free %":"98.35",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usoma01ep2genclu0010",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"48029.20",
             "Memory Free %":"97.80",
             "CPU (Virtual)":297,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.3",
             "Datastore":"usoma01ep2genclu0010-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1318.27",
             "Disk Free %":"98.28",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usoma01ep2genclu0004",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"33041.44",
             "Memory Free %":"67.28",
             "CPU (Virtual)":3799,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.3",
             "Datastore":"usoma01ep2genclu0004-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1140.03",
             "Disk Free %":"84.99",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usoma01ep2genclu0011",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"44111.20",
             "Memory Free %":"89.82",
             "CPU (Virtual)":1555,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"1.3",
             "Datastore":"usoma01ep2genclu0011-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1313.82",
             "Disk Free %":"97.95",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          }
       ]
    },
    {
       "CloudZone":"usjc201xp2vcawir1001.fiserv.one / usjc201p-wld1-vdc",
       "Description":"Production Johns Creek",
       "Metric CPU Ratio Max":"2.5",
       "Metric Memory Free %":"0",
       "Metric Disk Free %":"30",
       "Clusters":[
          {
             "Name":"usjc201ep2genclu0015",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"47037.70",
             "Memory Free %":"95.78",
             "CPU (Virtual)":637,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.6",
             "Datastore":"usjc201ep2genclu0015-vsan",
             "Disk Total (TiB)":"1299.45",
             "Disk Free (TiB)":"1244.30",
             "Disk Free %":"95.76",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usjc201ep2genclu0007",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"30593.29",
             "Memory Free %":"62.30",
             "CPU (Virtual)":4116,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.6",
             "Datastore":"usjc201ep2genclu0007-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1224.09",
             "Disk Free %":"91.26",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usjc201ep2genclu0006",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"32033.70",
             "Memory Free %":"65.23",
             "CPU (Virtual)":3628,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.1",
             "Datastore":"usjc201ep2genclu0006-vsan",
             "Disk Total (TiB)":"1299.45",
             "Disk Free (TiB)":"1190.56",
             "Disk Free %":"91.62",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usjc201ep2genclu0009",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"40237.44",
             "Memory Free %":"81.94",
             "CPU (Virtual)":2827,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.5",
             "Datastore":"usjc201ep2genclu0009-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1211.23",
             "Disk Free %":"90.30",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usjc201ep2genclu0008",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"30725.07",
             "Memory Free %":"62.57",
             "CPU (Virtual)":4165,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.6",
             "Datastore":"usjc201ep2genclu0008-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1206.31",
             "Disk Free %":"89.93",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usjc201ep2genclu0005",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"34967.95",
             "Memory Free %":"71.21",
             "CPU (Virtual)":2942,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.6",
             "Datastore":"usjc201ep2genclu0005-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"855.78",
             "Disk Free %":"63.80",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usjc201ep2genclu0001",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"33840.70",
             "Memory Free %":"68.91",
             "CPU (Virtual)":3777,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.3",
             "Datastore":"usjc201ep2genclu0001-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1227.79",
             "Disk Free %":"91.53",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usjc201ep2genclu0014",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"45821.95",
             "Memory Free %":"93.31",
             "CPU (Virtual)":819,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.7",
             "Datastore":"usjc201ep2genclu0014-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1300.60",
             "Disk Free %":"96.96",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usjc201ep2genclu0017",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"47587.70",
             "Memory Free %":"96.90",
             "CPU (Virtual)":443,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.4",
             "Datastore":"usjc201ep2genclu0017-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1281.70",
             "Disk Free %":"95.55",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usjc201ep2genclu0003",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"34710.27",
             "Memory Free %":"70.68",
             "CPU (Virtual)":2762,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.4",
             "Datastore":"usjc201ep2genclu0003-vsan",
             "Disk Total (TiB)":"1337.87",
             "Disk Free (TiB)":"942.64",
             "Disk Free %":"70.46",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usjc201ep2genclu0010",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"38250.38",
             "Memory Free %":"77.89",
             "CPU (Virtual)":2901,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.5",
             "Datastore":"usjc201ep2genclu0010-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1211.19",
             "Disk Free %":"90.30",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usjc201ep2genclu0002",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"36807.70",
             "Memory Free %":"74.95",
             "CPU (Virtual)":2804,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.4",
             "Datastore":"usjc201ep2genclu0002-vsan",
             "Disk Total (TiB)":"1299.45",
             "Disk Free (TiB)":"1050.80",
             "Disk Free %":"80.87",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usjc201ep2genclu0013",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"47395.70",
             "Memory Free %":"96.51",
             "CPU (Virtual)":227,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.2",
             "Datastore":"usjc201ep2genclu0013-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1316.87",
             "Disk Free %":"98.17",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usjc201ep2genclu0004",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"30914.95",
             "Memory Free %":"62.95",
             "CPU (Virtual)":3794,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.3",
             "Datastore":"usjc201ep2genclu0004-vsan",
             "Disk Total (TiB)":"1299.45",
             "Disk Free (TiB)":"844.84",
             "Disk Free %":"65.02",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usjc201ep2genclu0016",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"47547.70",
             "Memory Free %":"96.82",
             "CPU (Virtual)":647,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.6",
             "Datastore":"usjc201ep2genclu0016-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1319.32",
             "Disk Free %":"98.36",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usjc201ep2genclu0012",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"38765.74",
             "Memory Free %":"78.94",
             "CPU (Virtual)":3078,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.7",
             "Datastore":"usjc201ep2genclu0012-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1185.37",
             "Disk Free %":"88.37",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"usjc201ep2genclu0011",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"41740.12",
             "Memory Free %":"85.00",
             "CPU (Virtual)":2292,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"2.0",
             "Datastore":"usjc201ep2genclu0011-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1225.56",
             "Disk Free %":"91.37",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          }
       ]
    },
    {
       "CloudZone":"uschd02xp2vcawir1001.fiserv.one / uschd02p-wld1-vdc",
       "Description":"Production Phoenix",
       "Metric CPU Ratio Max":"2.5",
       "Metric Memory Free %":"0",
       "Metric Disk Free %":"30",
       "Clusters":[
          {
             "Name":"uschd02ep2genclu0006",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"47837.70",
             "Memory Free %":"97.41",
             "CPU (Virtual)":352,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.3",
             "Datastore":"uschd02ep2genclu0006-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1319.80",
             "Disk Free %":"98.39",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"uschd02ep2genclu0008",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"48819.70",
             "Memory Free %":"99.41",
             "CPU (Virtual)":80,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.1",
             "Datastore":"uschd02ep2genclu0008-vsan",
             "Disk Total (TiB)":"1299.45",
             "Disk Free (TiB)":"1273.46",
             "Disk Free %":"98.00",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"uschd02ep2genclu0005",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"47917.70",
             "Memory Free %":"97.58",
             "CPU (Virtual)":362,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.3",
             "Datastore":"uschd02ep2genclu0005-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1319.95",
             "Disk Free %":"98.40",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"uschd02ep2genclu0002",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"35653.70",
             "Memory Free %":"72.60",
             "CPU (Virtual)":3854,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.3",
             "Datastore":"uschd02ep2genclu0002-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1102.89",
             "Disk Free %":"82.22",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"uschd02ep2genclu0007",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"47997.95",
             "Memory Free %":"97.74",
             "CPU (Virtual)":247,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.2",
             "Datastore":"uschd02ep2genclu0007-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1308.83",
             "Disk Free %":"97.57",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"uschd02ep2genclu0001",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"34743.64",
             "Memory Free %":"70.75",
             "CPU (Virtual)":3969,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"3.4",
             "Datastore":"uschd02ep2genclu0001-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1138.06",
             "Disk Free %":"84.84",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          },
          {
             "Name":"uschd02ep2genclu0003",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"45332.70",
             "Memory Free %":"92.31",
             "CPU (Virtual)":969,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.8",
             "Datastore":"uschd02ep2genclu0003-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1250.98",
             "Disk Free %":"93.26",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"uschd02ep2genclu0004",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"46022.70",
             "Memory Free %":"93.72",
             "CPU (Virtual)":923,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"0.8",
             "Datastore":"uschd02ep2genclu0004-vsan",
             "Disk Total (TiB)":"1341.36",
             "Disk Free (TiB)":"1238.84",
             "Disk Free %":"92.36",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          }
       ]
    },
    {
       "CloudZone":"usljv04xl2vcawir1001.fiserv.one / usljv04n-wld1-vdc",
       "Description":"Nonproduction Lewisville",
       "Metric CPU Ratio Max":"7",
       "Metric Memory Free %":"-20",
       "Metric Disk Free %":"30",
       "Clusters":[
          {
             "Name":"usljv04en2genclu0004",
             "HostCount":"16",
             "Memory Total (GiB)":"24553.98",
             "Memory Free (GiB)":"10562.01",
             "Memory Free %":"43.02",
             "CPU (Virtual)":3898,
             "CPU (Physical)":576,
             "CPU Ratio (vCPU:pCPU)":"6.8",
             "Datastore":"usljv04en2genclu0004-vsan",
             "Disk Total (TiB)":"670.68",
             "Disk Free (TiB)":"519.75",
             "Disk Free %":"77.50",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"admin-disabled"
          },
          {
             "Name":"usljv04en2genclu0001",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"20253.45",
             "Memory Free %":"41.24",
             "CPU (Virtual)":6196,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"5.4",
             "Datastore":"usljv04en2genclu0001-vsan",
             "Disk Total (TiB)":"1341.37",
             "Disk Free (TiB)":"1043.54",
             "Disk Free %":"77.80",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          },
          {
             "Name":"usljv04en2genclu0003",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"21090.54",
             "Memory Free %":"42.95",
             "CPU (Virtual)":7068,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"6.1",
             "Datastore":"usljv04en2genclu0003-vsan",
             "Disk Total (TiB)":"1341.37",
             "Disk Free (TiB)":"1047.97",
             "Disk Free %":"78.13",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"admin-disabled"
          },
          {
             "Name":"usljv04en2genclu0002",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"26793.99",
             "Memory Free %":"54.56",
             "CPU (Virtual)":5489,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"4.8",
             "Datastore":"usljv04en2genclu0002-vsan",
             "Disk Total (TiB)":"1341.37",
             "Disk Free (TiB)":"1084.72",
             "Disk Free %":"80.87",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          }
       ]
    },
    {
       "CloudZone":"usoma01xl2vcawir1001.fiserv.one / usoma01n-wld1-vdc",
       "Description":"Nonproduction Omaha",
       "Metric CPU Ratio Max":"7",
       "Metric Memory Free %":"-20",
       "Metric Disk Free %":"30",
       "Clusters":[
          {
             "Name":"usoma01en2genclu0001",
             "HostCount":"32",
             "Memory Total (GiB)":"49107.95",
             "Memory Free (GiB)":"14819.20",
             "Memory Free %":"30.18",
             "CPU (Virtual)":8103,
             "CPU (Physical)":1152,
             "CPU Ratio (vCPU:pCPU)":"7.0",
             "Datastore":"usoma01en2genclu0001-vsan",
             "Disk Total (TiB)":"1257.53",
             "Disk Free (TiB)":"839.07",
             "Disk Free %":"66.72",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"disabled"
          }
       ]
    },
    {
       "CloudZone":"lxlpvcnc01.onefiserv.net / Nonproduction Lewisville Performance Lab",
       "Description":"Nonproduction Lewisville Performance Lab",
       "Metric CPU Ratio Max":"7",
       "Metric Memory Free %":"0",
       "Metric Disk Free %":"30",
       "Clusters":[
          {
             "Name":"bu-llp-c1",
             "HostCount":"28",
             "Memory Total (GiB)":"21465.40",
             "Memory Free (GiB)":"12249.40",
             "Memory Free %":"57.07",
             "CPU (Virtual)":2874,
             "CPU (Physical)":672,
             "CPU Ratio (vCPU:pCPU)":"4.3",
             "Datastore":"bu-llp-c1-vsan",
             "Disk Total (TiB)":"565.89",
             "Disk Free (TiB)":"469.57",
             "Disk Free %":"82.98",
             "Metric CPU Ratio Max":"",
             "Metric Memory Free %":"",
             "Metric Disk Free %":"",
             "Provisioning Status":"enabled"
          }
       ]
    }
 ]
  public clustersFromService = {};

  constructor(private clusterdataService: ClusterDataService) { }

  ngOnInit() {
     this.clustersFromService = this.clusterdataService.getClusters();
  }



}